version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: sweetshop-v2-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sweetshop_v2
      MYSQL_USER: sweetuser
      MYSQL_PASSWORD: sweetpass
    ports:
      - "3308:3306"
