services:
  - type: web
    name: sweet-shop
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 8082
      - key: SPRING_PROFILES_ACTIVE
        value: mysql
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: sweetshop-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: sweetshop-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: sweetshop-db
          property: password

databases:
  - name: sweetshop-db
    databaseName: sweetshop_v2
    user: sweetshop
    plan: free


